import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

import Navbar from '@/components/Navbar'
import Provider from '@/components/Provide'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'NAL E-Commerce',
  description: 'Generated by create next app',
  icons: {
    icon:'/favicon.ico',
  }
}
export const revalidate = 10
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi">
      <body className={inter.className}>
        <Provider>
          <Navbar/>
          {children}
          <Footer/>
        </Provider>
        </body>
    </html>
  )
}
